services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  project-management:
    build:
      context: ./project-management
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://13.51.163.189"
    container_name: p-management-frontend
    restart: always
    env_file:
      - ./project-management/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
