name: Deploy to EC2

on:
  push:
    branches:
      - master # ya 'dev', jis branch se deploy karna hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app   # yahan apni EC2 app directory likho
            git pull origin master
            docker compose down
            docker compose build --no-cache
            docker compose up -d
